services:
  postgres:
    image: postgres:16
    container_name: marketplace_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketplace_testtask
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_pass
    ports:
      - "5432:5432"
    volumes:
      - marketplace_pg_data:/var/lib/postgresql/data

volumes:
  marketplace_pg_data:
